// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webblabb2distor.Persistence;

#nullable disable

namespace webblabb2distor.Migrations
{
    [DbContext(typeof(UserDbcontext))]
    [Migration("20241115115727_User")]
    partial class User
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webblabb2distor.Persistence.UserDb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("UserDbs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Password = "Orvar123!",
                            Username = "Bertil@kth.se"
                        },
                        new
                        {
                            id = 2,
                            Password = "123Gaming",
                            Username = "Kalle@kth.se"
                        },
                        new
                        {
                            id = 3,
                            Password = "123Gaming",
                            Username = "bertil@kth.se"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
