// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webblabb2distor.Persistence;

#nullable disable

namespace webblabb2distor.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    [Migration("20241115115651_Auction")]
    partial class Auction
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webblabb2distor.Persistence.AuctionDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SellerUsername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AuctionDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            Description = "Auction description",
                            EndDateTime = new DateTime(2024, 11, 22, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "ragnar",
                            SellerUsername = "Seller",
                            StartingPrice = 45m
                        },
                        new
                        {
                            Id = -2,
                            Description = "Old ferrari",
                            EndDateTime = new DateTime(2024, 11, 25, 0, 0, 0, 0, DateTimeKind.Local),
                            Name = "bartil",
                            SellerUsername = "bertil",
                            StartingPrice = 25000m
                        });
                });

            modelBuilder.Entity("webblabb2distor.Persistence.BidsDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bidamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Biddername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Bidtime")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("BidsDbs");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            AuctionId = -1,
                            Bidamount = 35m,
                            Biddername = "byuer",
                            Bidtime = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = -2,
                            AuctionId = -2,
                            Bidamount = 20000m,
                            Biddername = "Kalle",
                            Bidtime = new DateTime(2024, 11, 23, 0, 0, 0, 0, DateTimeKind.Local)
                        },
                        new
                        {
                            Id = 1,
                            AuctionId = -1,
                            Bidamount = 50m,
                            Biddername = "ferrari@gmail.com",
                            Bidtime = new DateTime(2024, 11, 15, 12, 56, 51, 106, DateTimeKind.Local).AddTicks(3780)
                        });
                });

            modelBuilder.Entity("webblabb2distor.Persistence.BidsDb", b =>
                {
                    b.HasOne("webblabb2distor.Persistence.AuctionDB", "Auction")
                        .WithMany("BidsDbs")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("webblabb2distor.Persistence.AuctionDB", b =>
                {
                    b.Navigation("BidsDbs");
                });
#pragma warning restore 612, 618
        }
    }
}
