// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webblabb2distor.Persistence;

#nullable disable

namespace webblabb2distor.Migrations
{
    [DbContext(typeof(ProjectDbContext))]
    [Migration("20241014125328_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webblabb2distor.Persistence.ProjectDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ProjectDbs");

                    b.HasData(
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2024, 10, 14, 14, 53, 25, 496, DateTimeKind.Local).AddTicks(231),
                            Title = "testlearn Aspnet"
                        });
                });

            modelBuilder.Entity("webblabb2distor.Persistence.TaskDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("TasksDbs");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "test test la la",
                            LastUpdated = new DateTime(2024, 10, 14, 14, 53, 25, 496, DateTimeKind.Local).AddTicks(590),
                            ProjectId = 3
                        });
                });

            modelBuilder.Entity("webblabb2distor.Persistence.TaskDb", b =>
                {
                    b.HasOne("webblabb2distor.Persistence.ProjectDb", "Project")
                        .WithMany("TaskDbs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("webblabb2distor.Persistence.ProjectDb", b =>
                {
                    b.Navigation("TaskDbs");
                });
#pragma warning restore 612, 618
        }
    }
}
