// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webblabb2distor.Persistence;

#nullable disable

namespace webblabb2distor.Migrations
{
    [DbContext(typeof(AuctionDbContext))]
    partial class ProjectDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webblabb2distor.Persistence.AuctionDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Enddate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Sellername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("AuctionDbs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Enddate = new DateTime(2024, 10, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Sellername = "Seller",
                            description = "Auction description",
                            name = "ragnar",
                            price = 45m
                        },
                        new
                        {
                            Id = 2,
                            Enddate = new DateTime(2024, 10, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            Sellername = "bertil",
                            description = "Old ferrari",
                            name = "bartil",
                            price = 25000m
                        });
                });

            modelBuilder.Entity("webblabb2distor.Persistence.BidsDb", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("AuctionId")
                        .HasColumnType("int");

                    b.Property<decimal>("Bidamount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Biddername")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Bidtime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuctionId");

                    b.ToTable("BidsDbs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuctionId = 1,
                            Bidamount = 35m,
                            Biddername = "byuer",
                            Bidtime = new DateTime(2024, 10, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ProjectId = 0
                        },
                        new
                        {
                            Id = 2,
                            AuctionId = 2,
                            Bidamount = 20000m,
                            Biddername = "Kalle",
                            Bidtime = new DateTime(2024, 10, 17, 0, 0, 0, 0, DateTimeKind.Local),
                            ProjectId = 0
                        });
                });

            modelBuilder.Entity("webblabb2distor.Persistence.BidsDb", b =>
                {
                    b.HasOne("webblabb2distor.Persistence.AuctionDB", "Auction")
                        .WithMany("BidsDbs")
                        .HasForeignKey("AuctionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auction");
                });

            modelBuilder.Entity("webblabb2distor.Persistence.AuctionDB", b =>
                {
                    b.Navigation("BidsDbs");
                });
#pragma warning restore 612, 618
        }
    }
}
