// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using webblabb2distor.Persistence;

#nullable disable

namespace webblabb2distor.Migrations
{
    [DbContext(typeof(UserDbcontext))]
    partial class UserDbcontextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("webblabb2distor.Persistence.UserDb", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("UserDbs");

                    b.HasData(
                        new
                        {
                            id = 1,
                            Password = "123456",
                            Username = "bertil"
                        },
                        new
                        {
                            id = 2,
                            Password = "2222",
                            Username = "ragnar"
                        },
                        new
                        {
                            id = 3,
                            Password = "4444",
                            Username = "hagnar"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
